#!/bin/bash 

set -euo pipefail

XDG_CONFIG_HOME="$HOME/.config"

if if ! command -v chezmoi >/dev/null; then
	sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:crpruett/dotfiles.git
fi

if command -v alacritty >/dev/null;
then 
mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme "$XDG_CONFIG_HOME"/alacritty/themes
fi

sudo apt update
sudo apt install vim tmux bash-completion

exit 0
